### ISSUE TITLE
This mod is still not working for me i have seen people as it worked for what can I do?  

### ISSUE THREAD

**Issue by tierpmaskin** [w33zl/FS25_PowerTools#16] opened 2024-12-10 14:14 UTC
> **IMPORTANT!** Please be respectful of my time. If I don't get enough and/or specific details I really cannot investigate the issue. Please answer the questions below to the best of your ability, providing as much details and context as possible. 

**WHAT IS THE PROBLEM?**
> _A clear and concise description of what the bug is._

**HOW CAN I REPRODUCE THE ERROR?**
> E.g. first go to X, then do Y. The more details I get the greater is the chance that I can solve the issue.

**Screenshots or log information**
If applicable, add screenshots and/or errors and warnings from your log.txt to help explain your problem.

**Additional information (please complete the following information):**
 - Game version [e.g. v1.3]: 
 - Mod Version [e.g. 1.0.0.0]: 
 - Type of game client [e.g. Steam, Giants]: 
 - Do you play single or multiplayer [Singleplayer/Multiplayer]: 
 - Are you the host (if multiplayer) [yes/no]: 

**Additional context**

**Comment by w33zl** [comment] 2024-12-14 19:16
Duplicate of issue #9. Please don't make multiple error reports for the same issue, this just takes away time that I could spend on investigating the issues instead.

**Closed by w33zl** 2024-12-14 19:16 UTC
Labels: duplicate
