### ISSUE TITLE
Menu opens with R

### ISSUE THREAD

**Issue by Sthys69** [w33zl/FS25_PowerTools#5] opened 2024-11-29 02:17 UTC
**Describe the bug**
When trying to refill the John Deere C411R, the Power Tools Menu opens (R), even if unbinding / rebinding the doesn't solve the problem.

**To Reproduce**
1. Mount to John Deere C411R
2. Try to refill Wrapper foil

**Expected behavior**
Should refill your wrapper foil and select color of the foil

**Screenshots**
n/a

**Additional information (please complete the following information):**
 - Game version [1.3.0.0]
 - Mod Version [e.g. 1.0.0.0]
 - Game Provide [Steam]

**Comment by w33zl** [comment] 2024-12-17 13:15
Duplicate of #17

**Comment by w33zl** [comment] 2024-12-19 10:08
Since I haven't heard any new reports on this issue and no feedback on the hotfix I will consider this solved for now (and reopen an issue if needed)

**Closed by w33zl** 2024-12-19 10:08 UTC
Labels: bug, duplicate
