### ISSUE TITLE
Multiplayer Server not recognizing new version

### ISSUE THREAD

**Issue by Nmanory** [w33zl/FS25_PowerTools#22] opened 2024-12-17 16:15 UTC
> **IMPORTANT!** Please be respectful of my time. If I don't get enough and/or specific details I really cannot investigate the issue. Please answer the questions below to the best of your ability, providing as much details and context as possible. 

**WHAT IS THE PROBLEM?**
> just updated to PowerTools V1.0.1.  Using Apex multiplayer server I installed update both on my system and the server and confirmed version number.   When logging into the server in game I get an error that says Powertools v1.0.1 isn't available however it's in my correct mod directory and downloaded and activated within apex server......  Now after deleting all versions on my system and server and reinstalling 1.0.1.  Suddenly that error is now gone, but I can't login to the server as it gets stuck on loading at 57% and stays there.   If I remove Power Tools everything works fine 

**HOW CAN I REPRODUCE THE ERROR?**
> Try new version of Powertools on multiplayer server

**Screenshots or log information**
If applicable, add screenshots and/or errors and warnings from your log.txt to help explain your problem.

**Additional information (please complete the following information):**
 - Game version [e.g. v1.3]: Current as of 12/17
 - Mod Version [e.g. 1.0.0.0]: 1.0.1
 - Type of game client [e.g. Steam, Giants]: Steam
 - Do you play single or multiplayer [Singleplayer/Multiplayer]: Multi
 - Are you the host (if multiplayer) [yes/no]: It's a perpetual server through ApexHosting

**Additional context**

**Comment by w33zl** [comment] 2024-12-17 16:20
Duplicate of #21, see that issue for details.

**Closed by w33zl** 2024-12-17 16:20 UTC

**Comment by w33zl** [comment] 2024-12-18 08:11
No worries :)
